server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://119.29.105.157:3306/stock_master?useSSL=false&characterEncoding=utf-8&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: hy
    password: casa
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: 119.29.105.157
    port: 6379
    timeout: 1000
    database: 0
    password: casa
  cache:
    type: caffeine

ocr:
  service: chaojiyingOcrService
  third:
    aliyun:
      appcode:
    chaojiying:
      user:
      pass:
      softid: 000000

logging:
  file:
    name: /logs/stock-service.log
  logback:
    rollingpolicy:
      max-history: 30
  level:
    root: info
    org.springfromework.web: info
    org.springframework.jdbc: debug
